//! Python package code generation.
//!
//! Generates Python packages with class-based model APIs:
//!   model = DragModel(area=10.0, cd=0.3)
//!   result = model.predict(rho=1.225, velocity=20.0)

use crate::interface::{FieldDef, ModelInterface, RecordDef};
use crate::manifest::{MoltManifest, TargetConfig};
use anyhow::{Context, Result};
use base64::{engine::general_purpose::STANDARD as BASE64, Engine};
use heck::{ToSnakeCase, ToUpperCamelCase};
use std::collections::HashMap;
use std::path::Path;

/// Generate a complete Python package.
pub fn generate_python_package(
    manifest: &MoltManifest,
    models: &[ModelInterface],
    wasm_bytes: &HashMap<String, Vec<u8>>,
    output_dir: &Path,
    target_config: &TargetConfig,
) -> Result<()> {
    let package_name = target_config
        .package_name
        .clone()
        .unwrap_or_else(|| manifest.package.name.replace('-', "_"));

    // Create directory structure
    let pkg_dir = output_dir.join(&package_name);
    std::fs::create_dir_all(&pkg_dir)
        .with_context(|| format!("Failed to create package directory: {:?}", pkg_dir))?;

    // Generate pyproject.toml
    let pyproject = generate_pyproject_toml(manifest, &package_name);
    std::fs::write(output_dir.join("pyproject.toml"), pyproject)?;
    println!("  Generated pyproject.toml");

    // Generate README.md
    let readme = generate_readme(manifest, models, &package_name);
    std::fs::write(output_dir.join("README.md"), readme)?;
    println!("  Generated README.md");

    // Generate __init__.py
    let init_py = generate_init_py(models, &package_name);
    std::fs::write(pkg_dir.join("__init__.py"), init_py)?;
    println!("  Generated {}/__init__.py", package_name);

    // Generate _wasm.py with embedded WASM bytes
    let wasm_py = generate_wasm_py(wasm_bytes);
    std::fs::write(pkg_dir.join("_wasm.py"), wasm_py)?;
    println!("  Generated {}/_wasm.py", package_name);

    // Generate _runtime.py
    let runtime_py = generate_runtime_py(models);
    std::fs::write(pkg_dir.join("_runtime.py"), runtime_py)?;
    println!("  Generated {}/_runtime.py", package_name);

    // Generate py.typed marker for type hints
    std::fs::write(pkg_dir.join("py.typed"), "")?;

    // Generate model files
    for model in models {
        let model_py = generate_model_py(model);
        let filename = format!("{}.py", model.name.to_snake_case());
        std::fs::write(pkg_dir.join(&filename), model_py)?;
        println!("  Generated {}/{}", package_name, filename);
    }

    Ok(())
}

fn generate_pyproject_toml(manifest: &MoltManifest, package_name: &str) -> String {
    let description = if manifest.package.description.is_empty() {
        format!("{} - generated by molt", manifest.package.name)
    } else {
        manifest.package.description.clone()
    };

    let mut authors_toml = String::new();
    if !manifest.package.authors.is_empty() {
        let authors: Vec<String> = manifest
            .package
            .authors
            .iter()
            .map(|a| format!("{{ name = \"{}\" }}", a))
            .collect();
        authors_toml = format!("authors = [{}]\n", authors.join(", "));
    }

    let license_toml = manifest
        .package
        .license
        .as_ref()
        .map(|l| format!("license = \"{}\"\n", l))
        .unwrap_or_default();

    let repo_toml = manifest
        .package
        .repository
        .as_ref()
        .map(|r| format!("[project.urls]\nRepository = \"{}\"\n", r))
        .unwrap_or_default();

    format!(
        r#"[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{package_name}"
version = "{version}"
description = "{description}"
readme = "README.md"
requires-python = ">=3.10"
{authors_toml}{license_toml}dependencies = [
    "wasmtime>=21.0.0",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Typing :: Typed",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "mypy>=1.0",
]

{repo_toml}
[tool.hatch.build.targets.wheel]
packages = ["{package_name}"]
"#,
        package_name = package_name,
        version = manifest.package.version,
        description = description,
        authors_toml = authors_toml,
        license_toml = license_toml,
        repo_toml = repo_toml,
    )
}

fn generate_readme(
    manifest: &MoltManifest,
    models: &[ModelInterface],
    package_name: &str,
) -> String {
    let description = if manifest.package.description.is_empty() {
        format!("{} - generated by molt", manifest.package.name)
    } else {
        manifest.package.description.clone()
    };

    let mut model_docs = String::new();
    for model in models {
        let pascal_name = model.name.to_upper_camel_case();

        // Build param args
        let param_args: Vec<String> = model
            .params
            .fields
            .iter()
            .map(|f| format!("{}=...", f.name))
            .collect();

        // Build input args
        let input_args: Vec<String> = model
            .inputs
            .fields
            .iter()
            .map(|f| format!("{}=...", f.name))
            .collect();

        model_docs.push_str(&format!(
            r#"
### {pascal_name}Model

```python
from {package_name} import {pascal_name}Model

model = {pascal_name}Model({param_args})
result = model.predict({input_args})
```
"#,
            pascal_name = pascal_name,
            package_name = package_name,
            param_args = param_args.join(", "),
            input_args = input_args.join(", "),
        ));
    }

    format!(
        r#"# {package_name}

{description}

Generated by [molt](https://github.com/freol35241/molt).

## Installation

```bash
pip install {package_name}
```

## Usage
{model_docs}
"#,
        package_name = package_name,
        description = description,
        model_docs = model_docs,
    )
}

fn generate_init_py(models: &[ModelInterface], package_name: &str) -> String {
    let mut imports = Vec::new();
    let mut exports = Vec::new();

    for model in models {
        let snake_name = model.name.to_snake_case();
        let pascal_name = model.name.to_upper_camel_case();

        imports.push(format!(
            "from .{snake_name} import (\n    \
             {pascal_name}Model,\n    \
             {pascal_name}ModelError,\n    \
             {pascal_name}Params,\n    \
             {pascal_name}Outputs,\n\
             )",
            snake_name = snake_name,
            pascal_name = pascal_name
        ));

        exports.extend([
            format!("\"{}Model\"", pascal_name),
            format!("\"{}ModelError\"", pascal_name),
            format!("\"{}Params\"", pascal_name),
            format!("\"{}Outputs\"", pascal_name),
        ]);
    }

    format!(
        r#""""{pkg_name} - Generated by molt. Do not edit."""

{imports}

__all__ = [
    {exports},
]
"#,
        pkg_name = package_name,
        imports = imports.join("\n"),
        exports = exports.join(",\n    "),
    )
}

fn generate_wasm_py(wasm_bytes: &HashMap<String, Vec<u8>>) -> String {
    let mut module_entries = Vec::new();

    for (name, bytes) in wasm_bytes {
        let encoded = BASE64.encode(bytes);
        module_entries.push(format!(
            "    \"{name}\": base64.b64decode(\n        b\"{encoded}\"\n    )",
            name = name,
            encoded = encoded
        ));
    }

    format!(
        r#""""Embedded WASM module - Generated by molt. Do not edit."""

import base64

WASM_BYTES: bytes = base64.b64decode(
    b"{main_wasm}"
)

WASM_MODULES: dict[str, bytes] = {{
{entries}
}}
"#,
        main_wasm = wasm_bytes
            .get("main")
            .map(|b| BASE64.encode(b))
            .unwrap_or_default(),
        entries = module_entries.join(",\n")
    )
}

fn generate_runtime_py(models: &[ModelInterface]) -> String {
    // Build interface mapping (snake_case name -> full WIT interface path)
    let mut interface_names = Vec::new();
    for model in models {
        // Full interface path is "package/interface" e.g., "example:minimal/scale"
        let interface_path = format!("{}/{}", model.package, model.name);
        interface_names.push(format!(
            "    \"{}\": \"{}\",",
            model.name.to_snake_case(),
            interface_path
        ));
    }

    format!(
        r#""""Internal WASM runtime - Generated by molt. Do not edit."""
from __future__ import annotations
import threading
import weakref
from typing import Any
from collections import namedtuple

from wasmtime import Config, Engine, Store, WasiConfig
from wasmtime.component import Component, Linker

from ._wasm import WASM_BYTES

# Interface name mapping (snake_case -> full WIT interface path)
_INTERFACE_PATHS: dict[str, str] = {{
{interface_names}
}}

# WIT component model export names (constants to avoid magic strings)
_WIT_CONSTRUCTOR: str = "[constructor]model"
_WIT_PREDICT_METHOD: str = "[method]model.predict"

# Thread-safe singleton engine and component
_engine: Engine | None = None
_component: Component | None = None
_init_lock = threading.Lock()


def _get_engine() -> Engine:
    """Get or create the shared WASM engine (thread-safe)."""
    global _engine
    if _engine is None:
        with _init_lock:
            # Double-check locking pattern
            if _engine is None:
                config = Config()
                config.wasm_component_model = True
                _engine = Engine(config)
    return _engine


def _get_component() -> Component:
    """Get or create the component from WASM bytes (thread-safe)."""
    global _component
    if _component is None:
        with _init_lock:
            # Double-check locking pattern
            if _component is None:
                _component = Component(_get_engine(), WASM_BYTES)
    return _component


def _dict_to_namedtuple(d: dict[str, Any], name: str = "Record") -> Any:
    """Convert a dict to a namedtuple for wasmtime component API."""
    RecordType = namedtuple(name, d.keys())
    return RecordType(**d)


def _record_to_dict(record: Any) -> dict[str, Any]:
    """Convert a wasmtime Record to a dict."""
    if hasattr(record, "_fields"):
        # It's a namedtuple-like object
        return dict(zip(record._fields, record))
    elif hasattr(record, "__dict__"):
        return {{k: v for k, v in record.__dict__.items() if not k.startswith("_")}}
    else:
        # Try to iterate as if it has named attributes
        result = {{}}
        for attr in dir(record):
            if not attr.startswith("_"):
                val = getattr(record, attr, None)
                if not callable(val):
                    result[attr] = val
        return result


def _create_model(model_name: str, params: dict[str, Any]) -> "_ModelHandle":
    """
    Create a model instance.

    Returns a _ModelHandle that manages the WASM resources.
    Raises RuntimeError on failure.
    """
    engine = _get_engine()
    component = _get_component()

    # Create store with WASI configuration
    store = Store(engine)
    wasi_config = WasiConfig()
    wasi_config.inherit_env()
    wasi_config.inherit_stdout()
    wasi_config.inherit_stderr()
    store.set_wasi(wasi_config)

    # Create linker with WASI definitions
    linker = Linker(engine)
    linker.add_wasip2()

    # Instantiate the component
    instance = linker.instantiate(store, component)

    # Get the interface path for this model
    interface_path = _INTERFACE_PATHS.get(model_name, model_name)

    # Get the interface export
    export_idx = instance.get_export_index(store, interface_path)
    if export_idx is None:
        raise RuntimeError(f"Could not find interface '{{interface_path}}' in component")

    # Get the constructor function
    constructor_idx = instance.get_export_index(store, _WIT_CONSTRUCTOR, export_idx)
    if constructor_idx is None:
        raise RuntimeError(f"Could not find '{{_WIT_CONSTRUCTOR}}' in interface '{{interface_path}}'")
    constructor_fn = instance.get_func(store, constructor_idx)

    # Convert params dict to namedtuple
    params_nt = _dict_to_namedtuple(params, "Params")

    # Construct the model with params - may return result type
    result = constructor_fn(store, params_nt)
    constructor_fn.post_return(store)

    # Handle result type (ok, err) or plain value
    if isinstance(result, tuple) and len(result) == 2:
        ok_val, err_val = result
        if err_val is not None:
            raise RuntimeError(str(err_val))
        handle = ok_val
    else:
        handle = result

    # Store the interface info for predict calls
    return _ModelHandle(store, instance, handle, interface_path)


class _ModelHandle:
    """
    Internal handle for a model instance.

    Manages WASM resources and ensures proper cleanup when the model
    is no longer needed. Can be used as a context manager for explicit
    resource management.
    """

    __slots__ = ("_store", "_instance", "_handle", "_interface_path", "_predict_fn", "_closed")

    def __init__(self, store: Store, instance: Any, handle: Any, interface_path: str):
        self._store = store
        self._instance = instance
        self._handle = handle
        self._interface_path = interface_path
        self._predict_fn = None
        self._closed = False

    def _get_predict_fn(self) -> Any:
        if self._closed:
            raise RuntimeError("Model handle has been closed")
        if self._predict_fn is None:
            export_idx = self._instance.get_export_index(self._store, self._interface_path)
            predict_idx = self._instance.get_export_index(self._store, _WIT_PREDICT_METHOD, export_idx)
            if predict_idx is None:
                raise RuntimeError(f"Could not find '{{_WIT_PREDICT_METHOD}}' in interface '{{self._interface_path}}'")
            self._predict_fn = self._instance.get_func(self._store, predict_idx)
        return self._predict_fn

    def close(self) -> None:
        """Release WASM resources held by this model handle."""
        if not self._closed:
            self._closed = True
            # Clear references to allow garbage collection
            self._store = None  # type: ignore
            self._instance = None
            self._handle = None
            self._predict_fn = None

    def __del__(self) -> None:
        """Clean up resources when the handle is garbage collected."""
        self.close()

    def __enter__(self) -> "_ModelHandle":
        """Enter context manager."""
        return self

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        """Exit context manager and release resources."""
        self.close()


def _call_predict(handle: _ModelHandle, inputs: dict[str, Any]) -> dict[str, Any]:
    """
    Call predict on a model instance.

    Returns output dict.
    Raises RuntimeError on failure.
    """
    if handle._closed:
        raise RuntimeError("Model handle has been closed")

    predict_fn = handle._get_predict_fn()

    # Convert inputs dict to namedtuple
    inputs_nt = _dict_to_namedtuple(inputs, "Inputs")

    # Call predict - may return result type
    result = predict_fn(handle._store, handle._handle, inputs_nt)
    predict_fn.post_return(handle._store)

    # Handle result type (ok, err) or plain value
    if isinstance(result, tuple) and len(result) == 2:
        ok_val, err_val = result
        if err_val is not None:
            raise RuntimeError(str(err_val))
        return _record_to_dict(ok_val)
    else:
        return _record_to_dict(result)
"#,
        interface_names = interface_names.join("\n")
    )
}

fn generate_model_py(model: &ModelInterface) -> String {
    let snake_name = model.name.to_snake_case();
    let pascal_name = model.name.to_upper_camel_case();

    // Generate dataclass definitions
    let params_class = generate_dataclass(&model.params, &format!("{}Params", pascal_name));
    let outputs_class = generate_dataclass(&model.outputs, &format!("{}Outputs", pascal_name));

    // Generate the model class
    let model_class = generate_model_class(model, &snake_name, &pascal_name);

    format!(
        r#""""{model_name} model - Generated by molt. Do not edit."""
from dataclasses import dataclass

from ._runtime import _create_model, _call_predict


{params_class}


{outputs_class}


class {pascal_name}ModelError(Exception):
    """Error raised by {pascal_name}Model operations."""
    pass


{model_class}
"#,
        model_name = model.name,
        pascal_name = pascal_name,
        params_class = params_class,
        outputs_class = outputs_class,
        model_class = model_class,
    )
}

fn generate_dataclass(record: &RecordDef, class_name: &str) -> String {
    let fields: Vec<String> = record
        .fields
        .iter()
        .map(|f| {
            let py_type = f.ty.to_python();
            let doc_comment = f
                .docs
                .as_ref()
                .map(|d| format!("    # {}\n", d.trim()))
                .unwrap_or_default();
            format!("{}    {}: {}", doc_comment, f.name, py_type)
        })
        .collect();

    format!(
        r#"@dataclass(frozen=True)
class {class_name}:
    """Record type for {class_name}."""

{fields}"#,
        class_name = class_name,
        fields = fields.join("\n")
    )
}

fn generate_param_list(fields: &[FieldDef]) -> String {
    fields
        .iter()
        .map(|f| format!("{}: {}", f.name, f.ty.to_python()))
        .collect::<Vec<_>>()
        .join(", ")
}

fn generate_model_class(model: &ModelInterface, snake_name: &str, pascal_name: &str) -> String {
    let params_args = generate_param_list(&model.params.fields);
    let params_dict_entries: Vec<String> = model
        .params
        .fields
        .iter()
        .map(|f| format!("'{}': {}", f.wit_name, f.name))
        .collect();

    let inputs_args = generate_param_list(&model.inputs.fields);
    let inputs_dict_entries: Vec<String> = model
        .inputs
        .fields
        .iter()
        .map(|f| format!("'{}': {}", f.wit_name, f.name))
        .collect();

    let output_fields: Vec<String> = model
        .outputs
        .fields
        .iter()
        .map(|f| {
            format!(
                "{}=raw.get('{}', raw.get('{}'))",
                f.name, f.wit_name, f.name
            )
        })
        .collect();

    // Generate __init__ docstring with parameter descriptions
    let param_docs: Vec<String> = model
        .params
        .fields
        .iter()
        .map(|f| {
            let doc = f.docs.as_ref().map(|d| d.trim()).unwrap_or("");
            format!("            {}: {}", f.name, doc)
        })
        .collect();

    // Generate predict docstring with input descriptions
    let input_docs: Vec<String> = model
        .inputs
        .fields
        .iter()
        .map(|f| {
            let doc = f.docs.as_ref().map(|d| d.trim()).unwrap_or("");
            format!("            {}: {}", f.name, doc)
        })
        .collect();

    // Generate repr field list
    let repr_fields: Vec<String> = model
        .params
        .fields
        .iter()
        .map(|f| format!("{}={{self._params.{}}}", f.name, f.name))
        .collect();

    format!(
        r#"class {pascal_name}Model:
    """
    {model_name} model.

    Example:
        model = {pascal_name}Model({example_params})
        result = model.predict({example_inputs})
        print(result)
    """

    __slots__ = ('_handle', '_params')

    def __init__(self, {params_args}) -> None:
        """
        Create a {model_name} model.

        Args:
{param_docs}

        Raises:
            {pascal_name}ModelError: If parameters are invalid.
        """
        try:
            self._handle = _create_model(
                '{snake_name}',
                {{{params_dict}}}
            )
        except RuntimeError as e:
            raise {pascal_name}ModelError(str(e)) from None
        self._params = {pascal_name}Params({params_constructor})

    @property
    def params(self) -> {pascal_name}Params:
        """Parameters this model was constructed with."""
        return self._params

    def predict(self, {inputs_args}) -> {pascal_name}Outputs:
        """
        Predict outputs from inputs.

        Args:
{input_docs}

        Returns:
            {pascal_name}Outputs with computed values.

        Raises:
            {pascal_name}ModelError: If prediction fails.
        """
        try:
            raw = _call_predict(
                self._handle,
                {{{inputs_dict}}}
            )
        except RuntimeError as e:
            raise {pascal_name}ModelError(str(e)) from None
        return {pascal_name}Outputs(
            {output_fields}
        )

    def __repr__(self) -> str:
        return f"{pascal_name}Model({repr_fields})""#,
        snake_name = snake_name,
        pascal_name = pascal_name,
        model_name = model.name,
        params_args = params_args,
        inputs_args = inputs_args,
        param_docs = param_docs.join("\n"),
        input_docs = input_docs.join("\n"),
        example_params = model
            .params
            .fields
            .iter()
            .map(|f| format!("{}=...", f.name))
            .collect::<Vec<_>>()
            .join(", "),
        example_inputs = model
            .inputs
            .fields
            .iter()
            .map(|f| format!("{}=...", f.name))
            .collect::<Vec<_>>()
            .join(", "),
        params_constructor = model
            .params
            .fields
            .iter()
            .map(|f| format!("{}={}", f.name, f.name))
            .collect::<Vec<_>>()
            .join(", "),
        params_dict = params_dict_entries.join(", "),
        inputs_dict = inputs_dict_entries.join(", "),
        output_fields = output_fields.join(",\n            "),
        repr_fields = repr_fields.join(", "),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::interface::{FieldDef, ModelInterface, RecordDef, WitType};

    fn make_test_model() -> ModelInterface {
        ModelInterface {
            name: "drag".to_string(),
            package: "myorg:physics".to_string(),
            world: "drag-model".to_string(),
            export_path: "myorg:physics/drag/model".to_string(),
            params: RecordDef {
                name: "Params".to_string(),
                fields: vec![
                    FieldDef {
                        name: "area".to_string(),
                        wit_name: "area".to_string(),
                        ty: WitType::Float64,
                        docs: Some("Reference area [m²]".to_string()),
                    },
                    FieldDef {
                        name: "cd".to_string(),
                        wit_name: "cd".to_string(),
                        ty: WitType::Float64,
                        docs: Some("Drag coefficient [-]".to_string()),
                    },
                ],
            },
            inputs: RecordDef {
                name: "Inputs".to_string(),
                fields: vec![
                    FieldDef {
                        name: "rho".to_string(),
                        wit_name: "rho".to_string(),
                        ty: WitType::Float64,
                        docs: None,
                    },
                    FieldDef {
                        name: "velocity".to_string(),
                        wit_name: "velocity".to_string(),
                        ty: WitType::Float64,
                        docs: None,
                    },
                ],
            },
            outputs: RecordDef {
                name: "Outputs".to_string(),
                fields: vec![
                    FieldDef {
                        name: "drag_force".to_string(),
                        wit_name: "drag-force".to_string(),
                        ty: WitType::Float64,
                        docs: None,
                    },
                    FieldDef {
                        name: "dynamic_pressure".to_string(),
                        wit_name: "dynamic-pressure".to_string(),
                        ty: WitType::Float64,
                        docs: None,
                    },
                ],
            },
        }
    }

    #[test]
    fn test_generate_dataclass() {
        let model = make_test_model();
        let output = generate_dataclass(&model.params, "DragParams");
        assert!(output.contains("@dataclass(frozen=True)"));
        assert!(output.contains("class DragParams:"));
        assert!(output.contains("area: float"));
        assert!(output.contains("cd: float"));
    }

    #[test]
    fn test_generate_model_py() {
        let model = make_test_model();
        let output = generate_model_py(&model);
        assert!(output.contains("class DragParams:"));
        assert!(output.contains("class DragOutputs:"));
        assert!(output.contains("class DragModel:"));
        assert!(output.contains("class DragModelError(Exception):"));
        assert!(output.contains("def predict(self"));
    }

    #[test]
    fn test_generate_init_py() {
        let models = vec![make_test_model()];
        let output = generate_init_py(&models, "physics_models");
        assert!(output.contains("from .drag import"));
        assert!(output.contains("DragModel"));
        assert!(output.contains("DragModelError"));
        assert!(output.contains("DragParams"));
        assert!(output.contains("DragOutputs"));
    }
}
