//! Python package code generation.

use crate::interface::{FieldDef, ModelInterface, RecordDef};
use crate::manifest::{MoltManifest, TargetConfig};
use anyhow::{Context, Result};
use base64::{engine::general_purpose::STANDARD as BASE64, Engine};
use heck::{ToSnakeCase, ToUpperCamelCase};
use std::collections::HashMap;
use std::path::Path;

/// Generate a complete Python package.
pub fn generate_python_package(
    manifest: &MoltManifest,
    models: &[ModelInterface],
    wasm_bytes: &HashMap<String, Vec<u8>>,
    output_dir: &Path,
    target_config: &TargetConfig,
) -> Result<()> {
    let package_name = target_config
        .package_name
        .clone()
        .unwrap_or_else(|| manifest.package.name.replace('-', "_"));

    // Create directory structure
    let pkg_dir = output_dir.join(&package_name);
    std::fs::create_dir_all(&pkg_dir)
        .with_context(|| format!("Failed to create package directory: {:?}", pkg_dir))?;

    // Generate pyproject.toml
    let pyproject = generate_pyproject_toml(manifest, &package_name);
    std::fs::write(output_dir.join("pyproject.toml"), pyproject)?;
    println!("  Generated pyproject.toml");

    // Generate __init__.py
    let init_py = generate_init_py(models, &package_name);
    std::fs::write(pkg_dir.join("__init__.py"), init_py)?;
    println!("  Generated {}/__init__.py", package_name);

    // Generate _wasm.py with embedded WASM bytes
    let wasm_py = generate_wasm_py(wasm_bytes);
    std::fs::write(pkg_dir.join("_wasm.py"), wasm_py)?;
    println!("  Generated {}/_wasm.py", package_name);

    // Generate _runtime.py
    let runtime_py = generate_runtime_py(models);
    std::fs::write(pkg_dir.join("_runtime.py"), runtime_py)?;
    println!("  Generated {}/_runtime.py", package_name);

    // Generate py.typed marker for type hints
    std::fs::write(pkg_dir.join("py.typed"), "")?;

    // Generate model files
    for model in models {
        let model_py = generate_model_py(model);
        let filename = format!("{}.py", model.name.to_snake_case());
        std::fs::write(pkg_dir.join(&filename), model_py)?;
        println!("  Generated {}/{}", package_name, filename);
    }

    Ok(())
}

fn generate_pyproject_toml(manifest: &MoltManifest, package_name: &str) -> String {
    let description = if manifest.package.description.is_empty() {
        format!("{} - generated by molt", manifest.package.name)
    } else {
        manifest.package.description.clone()
    };

    let mut authors_toml = String::new();
    if !manifest.package.authors.is_empty() {
        let authors: Vec<String> = manifest
            .package
            .authors
            .iter()
            .map(|a| format!("{{ name = \"{}\" }}", a))
            .collect();
        authors_toml = format!("authors = [{}]\n", authors.join(", "));
    }

    let license_toml = manifest
        .package
        .license
        .as_ref()
        .map(|l| format!("license = \"{}\"\n", l))
        .unwrap_or_default();

    let repo_toml = manifest
        .package
        .repository
        .as_ref()
        .map(|r| format!("[project.urls]\nRepository = \"{}\"\n", r))
        .unwrap_or_default();

    format!(
        r#"[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "{package_name}"
version = "{version}"
description = "{description}"
readme = "README.md"
requires-python = ">=3.10"
{authors_toml}{license_toml}dependencies = [
    "wasmtime>=21.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "mypy>=1.0",
]

{repo_toml}
[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"*" = ["py.typed"]
"#,
        package_name = package_name,
        version = manifest.package.version,
        description = description,
        authors_toml = authors_toml,
        license_toml = license_toml,
        repo_toml = repo_toml,
    )
}

fn generate_init_py(models: &[ModelInterface], _package_name: &str) -> String {
    let mut imports = Vec::new();
    let mut exports = Vec::new();

    for model in models {
        let snake_name = model.name.to_snake_case();
        let pascal_name = model.name.to_upper_camel_case();

        imports.push(format!(
            "from .{snake_name} import (\n    \
             {pascal_name}Params,\n    \
             {pascal_name}Inputs,\n    \
             {pascal_name}Outputs,\n    \
             {pascal_name}ModelFn,\n    \
             create_{snake_name},\n\
             )",
            snake_name = snake_name,
            pascal_name = pascal_name
        ));

        exports.extend([
            format!("\"{}Params\"", pascal_name),
            format!("\"{}Inputs\"", pascal_name),
            format!("\"{}Outputs\"", pascal_name),
            format!("\"{}ModelFn\"", pascal_name),
            format!("\"create_{}\"", snake_name),
        ]);
    }

    format!(
        r#""""{pkg_name} - Generated by molt. Do not edit."""

{imports}

__all__ = [
    {exports},
]
"#,
        pkg_name = _package_name,
        imports = imports.join("\n"),
        exports = exports.join(",\n    "),
    )
}

fn generate_wasm_py(wasm_bytes: &HashMap<String, Vec<u8>>) -> String {
    let mut module_entries = Vec::new();

    for (name, bytes) in wasm_bytes {
        let encoded = BASE64.encode(bytes);
        module_entries.push(format!(
            "    \"{name}\": base64.b64decode(\n        b\"{encoded}\"\n    )",
            name = name,
            encoded = encoded
        ));
    }

    format!(
        r#""""Internal WASM modules - Generated by molt. Do not edit."""

import base64

WASM_MODULES: dict[str, bytes] = {{
{entries}
}}
"#,
        entries = module_entries.join(",\n")
    )
}

fn generate_runtime_py(models: &[ModelInterface]) -> String {
    // Extract unique package names for imports
    let packages: Vec<&str> = models.iter().map(|m| m.package.as_str()).collect();
    let _unique_package = packages.first().unwrap_or(&"");

    // Build interface mapping (model snake_name -> full WIT interface path)
    let mut interface_names = Vec::new();
    for model in models {
        // Full WIT interface path is "package/interface" e.g. "myorg:physics/drag"
        let wit_interface_path = format!("{}/{}", model.package, model.name);
        interface_names.push(format!(
            "    \"{}\": \"{}\",",
            model.name.to_snake_case(),
            wit_interface_path
        ));
    }

    format!(
        r#""""Internal WASM runtime - Generated by molt. Do not edit."""

from typing import Any

from wasmtime import Config, Engine, Store
from wasmtime.component import Component, Linker, Record

from ._wasm import WASM_MODULES

# Interface name mapping (snake_case -> WIT interface path)
_INTERFACE_NAMES: dict[str, str] = {{
{interface_names}
}}

# Singleton engine (thread-safe)
_engine: Engine | None = None
_components: dict[str, Component] = {{}}


def _get_engine() -> Engine:
    """Get or create the shared WASM engine."""
    global _engine
    if _engine is None:
        config = Config()
        config.wasm_component_model = True
        _engine = Engine(config)
    return _engine


def _get_component(name: str = "main") -> Component:
    """Get or create a component from WASM bytes."""
    if name not in _components:
        engine = _get_engine()
        wasm_bytes = WASM_MODULES.get(name)
        if wasm_bytes is None:
            raise ValueError(f"Unknown WASM module: {{name}}")
        _components[name] = Component(engine, wasm_bytes)
    return _components[name]


def _dict_to_record(d: dict[str, Any]) -> Record:
    """Convert a dictionary to a wasmtime Record."""
    record = Record()
    for key, value in d.items():
        setattr(record, key, value)
    return record


def _record_to_dict(record: Record) -> dict[str, Any]:
    """Convert a wasmtime Record to a dictionary."""
    if hasattr(record, '__dict__'):
        return dict(record.__dict__)
    return {{}}


class ModelHandle:
    """Wrapper for a model instance with its store."""

    __slots__ = ("_store", "_instance", "_model_resource", "_step_func")

    def __init__(
        self,
        store: Store,
        instance: Any,
        model_resource: Any,
        step_func: Any,
    ):
        self._store = store
        self._instance = instance
        self._model_resource = model_resource
        self._step_func = step_func

    def step(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """Call the step method with inputs, return outputs as dict."""
        inputs_record = _dict_to_record(inputs)
        result = self._step_func(self._store, self._model_resource, inputs_record)
        self._step_func.post_return(self._store)
        return _record_to_dict(result)


def create_model_instance(
    model_name: str,
    params: dict[str, Any],
) -> ModelHandle:
    """
    Create a new model instance.

    Args:
        model_name: Name of the model (snake_case)
        params: Dictionary of parameter values

    Returns:
        ModelHandle that can be used to call step()
    """
    engine = _get_engine()
    component = _get_component("main")
    store = Store(engine)

    # Create linker with WASI support and instantiate component
    linker = Linker(engine)
    linker.add_wasip2()
    instance = linker.instantiate(store, component)

    # Get the interface name for this model
    wit_interface = _INTERFACE_NAMES.get(model_name, model_name)

    # Navigate to the interface export
    interface_idx = instance.get_export_index(store, wit_interface)
    if interface_idx is None:
        raise RuntimeError(f"Could not find interface '{{wit_interface}}' in component")

    # Get the constructor function [constructor]model
    constructor_idx = instance.get_export_index(store, "[constructor]model", interface_idx)
    if constructor_idx is None:
        raise RuntimeError(f"Could not find constructor in interface '{{wit_interface}}'")
    constructor_func = instance.get_func(store, constructor_idx)

    # Get the step method [method]model.step
    step_idx = instance.get_export_index(store, "[method]model.step", interface_idx)
    if step_idx is None:
        raise RuntimeError(f"Could not find step method in interface '{{wit_interface}}'")
    step_func = instance.get_func(store, step_idx)

    # Create params record and call constructor
    params_record = _dict_to_record(params)
    model_resource = constructor_func(store, params_record)
    constructor_func.post_return(store)

    return ModelHandle(store, instance, model_resource, step_func)
"#,
        interface_names = interface_names.join("\n")
    )
}

fn generate_model_py(model: &ModelInterface) -> String {
    let snake_name = model.name.to_snake_case();
    let pascal_name = model.name.to_upper_camel_case();

    // Generate dataclass definitions
    let params_class = generate_dataclass(&model.params, &format!("{}Params", pascal_name));
    let inputs_class = generate_dataclass(&model.inputs, &format!("{}Inputs", pascal_name));
    let outputs_class = generate_dataclass(&model.outputs, &format!("{}Outputs", pascal_name));

    // Generate protocol for type hints
    let inputs_args = generate_param_list(&model.inputs.fields);

    // Generate the create function
    let create_func = generate_create_function(model, &snake_name, &pascal_name);

    format!(
        r#""""{model_name} model - Generated by molt. Do not edit."""

from dataclasses import dataclass
from typing import Protocol

from ._runtime import create_model_instance


{params_class}

{inputs_class}

{outputs_class}


class {pascal_name}ModelFn(Protocol):
    """Type signature for prepared {model_name} model."""

    params: {pascal_name}Params

    def __call__(self, {inputs_args}) -> {pascal_name}Outputs:
        """Compute model outputs from inputs."""
        ...


{create_func}
"#,
        model_name = model.name,
        pascal_name = pascal_name,
        params_class = params_class,
        inputs_class = inputs_class,
        outputs_class = outputs_class,
        inputs_args = inputs_args,
    )
}

fn generate_dataclass(record: &RecordDef, class_name: &str) -> String {
    let fields: Vec<String> = record
        .fields
        .iter()
        .map(|f| {
            let py_type = f.ty.to_python();
            let doc_comment = f
                .docs
                .as_ref()
                .map(|d| format!("    # {}\n", d.trim()))
                .unwrap_or_default();
            format!("{}    {}: {}", doc_comment, f.name, py_type)
        })
        .collect();

    format!(
        r#"@dataclass(frozen=True)
class {class_name}:
    """Record type for {class_name}."""

{fields}"#,
        class_name = class_name,
        fields = fields.join("\n")
    )
}

fn generate_param_list(fields: &[FieldDef]) -> String {
    fields
        .iter()
        .map(|f| format!("{}: {}", f.name, f.ty.to_python()))
        .collect::<Vec<_>>()
        .join(", ")
}

fn generate_create_function(model: &ModelInterface, snake_name: &str, pascal_name: &str) -> String {
    let params_args = generate_param_list(&model.params.fields);
    let params_dict_entries: Vec<String> = model
        .params
        .fields
        .iter()
        .map(|f| format!("\"{}\": {}", f.wit_name, f.name))
        .collect();

    let inputs_args = generate_param_list(&model.inputs.fields);
    let inputs_dict_entries: Vec<String> = model
        .inputs
        .fields
        .iter()
        .map(|f| format!("\"{}\": {}", f.wit_name, f.name))
        .collect();

    let output_fields: Vec<String> = model
        .outputs
        .fields
        .iter()
        .map(|f| {
            format!(
                "{}=raw.get(\"{}\", raw.get(\"{}\"))",
                f.name, f.wit_name, f.name
            )
        })
        .collect();

    // Generate docstring with parameter descriptions
    let param_docs: Vec<String> = model
        .params
        .fields
        .iter()
        .map(|f| {
            let doc = f.docs.as_ref().map(|d| d.trim()).unwrap_or("");
            format!("        {}: {}", f.name, doc)
        })
        .collect();

    format!(
        r#"def create_{snake_name}({params_args}) -> {pascal_name}ModelFn:
    """
    Create a {model_name} model with fixed parameters.

    Args:
{param_docs}

    Returns:
        A callable: ({inputs_sig}) -> {pascal_name}Outputs

    Example:
        model = create_{snake_name}({example_params})
        result = model({example_inputs})
    """
    params = {pascal_name}Params({params_constructor})
    handle = create_model_instance("{snake_name}", {{
        {params_dict}
    }})

    def model({inputs_args}) -> {pascal_name}Outputs:
        raw = handle.step({{
            {inputs_dict}
        }})
        return {pascal_name}Outputs(
            {output_fields}
        )

    model.params = params  # type: ignore[attr-defined]
    return model  # type: ignore[return-value]"#,
        snake_name = snake_name,
        pascal_name = pascal_name,
        model_name = model.name,
        params_args = params_args,
        inputs_args = inputs_args,
        inputs_sig = model
            .inputs
            .fields
            .iter()
            .map(|f| f.name.clone())
            .collect::<Vec<_>>()
            .join(", "),
        param_docs = param_docs.join("\n"),
        example_params = model
            .params
            .fields
            .iter()
            .map(|f| format!("{}=...", f.name))
            .collect::<Vec<_>>()
            .join(", "),
        example_inputs = model
            .inputs
            .fields
            .iter()
            .map(|f| format!("{}=...", f.name))
            .collect::<Vec<_>>()
            .join(", "),
        params_constructor = model
            .params
            .fields
            .iter()
            .map(|f| format!("{}={}", f.name, f.name))
            .collect::<Vec<_>>()
            .join(", "),
        params_dict = params_dict_entries.join(",\n        "),
        inputs_dict = inputs_dict_entries.join(",\n            "),
        output_fields = output_fields.join(",\n            "),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::interface::{FieldDef, ModelInterface, RecordDef, WitType};

    fn make_test_model() -> ModelInterface {
        ModelInterface {
            name: "drag".to_string(),
            package: "myorg:physics".to_string(),
            params: RecordDef {
                name: "Params".to_string(),
                fields: vec![
                    FieldDef {
                        name: "area".to_string(),
                        wit_name: "area".to_string(),
                        ty: WitType::Float64,
                        docs: Some("Reference area [m²]".to_string()),
                    },
                    FieldDef {
                        name: "cd".to_string(),
                        wit_name: "cd".to_string(),
                        ty: WitType::Float64,
                        docs: Some("Drag coefficient [-]".to_string()),
                    },
                ],
            },
            inputs: RecordDef {
                name: "Inputs".to_string(),
                fields: vec![
                    FieldDef {
                        name: "rho".to_string(),
                        wit_name: "rho".to_string(),
                        ty: WitType::Float64,
                        docs: None,
                    },
                    FieldDef {
                        name: "velocity".to_string(),
                        wit_name: "velocity".to_string(),
                        ty: WitType::Float64,
                        docs: None,
                    },
                ],
            },
            outputs: RecordDef {
                name: "Outputs".to_string(),
                fields: vec![
                    FieldDef {
                        name: "drag_force".to_string(),
                        wit_name: "drag-force".to_string(),
                        ty: WitType::Float64,
                        docs: None,
                    },
                    FieldDef {
                        name: "dynamic_pressure".to_string(),
                        wit_name: "dynamic-pressure".to_string(),
                        ty: WitType::Float64,
                        docs: None,
                    },
                ],
            },
        }
    }

    #[test]
    fn test_generate_dataclass() {
        let model = make_test_model();
        let output = generate_dataclass(&model.params, "DragParams");
        assert!(output.contains("@dataclass(frozen=True)"));
        assert!(output.contains("class DragParams:"));
        assert!(output.contains("area: float"));
        assert!(output.contains("cd: float"));
    }

    #[test]
    fn test_generate_model_py() {
        let model = make_test_model();
        let output = generate_model_py(&model);
        assert!(output.contains("class DragParams:"));
        assert!(output.contains("class DragInputs:"));
        assert!(output.contains("class DragOutputs:"));
        assert!(output.contains("def create_drag("));
        assert!(output.contains("-> DragModelFn:"));
    }
}
