//! Generate glue code that bridges WIT interfaces to user Rust implementations.
//!
//! This module creates `molt-gen/lib.rs` which:
//! - Includes user implementation modules via `#[path = "..."]`
//! - Generates wit_bindgen macros
//! - Creates adapter structs that implement the WIT guest traits

use crate::interface::ModelInterface;
use crate::manifest::{ModelConfig, MoltManifest};
use anyhow::{Context, Result};
use heck::{ToPascalCase, ToSnakeCase};
use std::collections::HashMap;
use std::path::Path;

/// Generate the glue code for molt-gen/lib.rs.
pub fn generate_glue(
    manifest: &MoltManifest,
    models: &[ModelInterface],
    _project_dir: &Path,
) -> Result<String> {
    let mut out = String::new();

    // Header
    out.push_str("//! Generated by molt. Do not edit.\n");
    out.push_str("//!\n");
    out.push_str("//! This file bridges WIT interfaces to user implementations.\n\n");

    // Build a map from model name to config for easy lookup
    let config_map: HashMap<&str, &ModelConfig> = manifest
        .models
        .iter()
        .map(|(name, config)| (name.as_str(), config))
        .collect();

    // Include user implementation modules
    out.push_str("// User implementation modules\n");
    for (name, config) in &manifest.models {
        let source_path = config.source.display();
        let module_name = name.to_snake_case();
        out.push_str(&format!(
            "#[path = \"../{source_path}\"]\nmod {module_name}_impl;\n",
            source_path = source_path,
            module_name = module_name
        ));
    }
    out.push('\n');

    // Generate the wit_bindgen! macro invocation
    out.push_str(&generate_wit_bindgen_macro(models));
    out.push('\n');

    // Generate use statements
    out.push_str(&generate_use_statements(models));
    out.push('\n');

    // Generate adapter structs for each model
    for model in models {
        if let Some(config) = config_map.get(model.name.as_str()) {
            out.push_str(&generate_adapter(model, config));
            out.push('\n');
        }
    }

    // Generate export! macro
    out.push_str(&generate_export_macro(models, &config_map));

    Ok(out)
}

/// Generate the wit_bindgen::generate! macro call.
fn generate_wit_bindgen_macro(models: &[ModelInterface]) -> String {
    let mut out = String::new();

    // We need to determine the world name - for now, use the first model's world
    // In a multi-model setup, they should all export to the same world
    let world = models
        .first()
        .map(|m| m.world.as_str())
        .unwrap_or("unknown");

    out.push_str("// Generate WIT bindings\n");
    out.push_str("wit_bindgen::generate!({\n");
    out.push_str(&format!("    world: \"{}\",\n", world));
    out.push_str("});\n");

    out
}

/// Generate use statements for WIT-generated types.
fn generate_use_statements(models: &[ModelInterface]) -> String {
    let mut out = String::new();
    out.push_str("// Import WIT-generated types\n");

    for model in models {
        let snake_name = model.name.to_snake_case();
        let pascal_name = model.name.to_pascal_case();

        // Parse package name (e.g., "myorg:physics" -> "myorg::physics")
        let package_path = model.package.replace(':', "::");

        out.push_str(&format!(
            "use exports::{}::{}::{{
    Guest as {pascal_name}Guest,
    GuestModel as Guest{pascal_name}Model,
    Inputs as {pascal_name}Inputs,
    Outputs as {pascal_name}Outputs,
    Params as {pascal_name}Params,
}};\n",
            package_path,
            snake_name,
            pascal_name = pascal_name
        ));
    }

    out
}

/// Generate an adapter struct for a single model.
fn generate_adapter(model: &ModelInterface, config: &ModelConfig) -> String {
    let mut out = String::new();
    let snake_name = model.name.to_snake_case();
    let pascal_name = model.name.to_pascal_case();
    let adapter_name = format!("{}ModelAdapter", pascal_name);
    let guest_struct_name = format!("{}GuestImpl", pascal_name);
    let user_struct = &config.struct_name;

    out.push_str(
        "// ============================================================================\n",
    );
    out.push_str(&format!("// {} Model Adapter\n", pascal_name));
    out.push_str(
        "// ============================================================================\n\n",
    );

    // Generate the adapter struct that holds the user implementation
    out.push_str(&format!("pub struct {} {{\n", adapter_name));
    out.push_str(&format!(
        "    inner: {}_impl::{},\n",
        snake_name, user_struct
    ));
    out.push_str("}\n\n");

    // Implement GuestModel for the adapter
    out.push_str(&format!(
        "impl Guest{}Model for {} {{\n",
        pascal_name, adapter_name
    ));

    // Constructor - WIT constructors can't return Result, so we panic on error
    out.push_str(&format!(
        "    fn new(p: {}Params) -> Self {{\n",
        pascal_name
    ));

    // Build parameter list from model interface
    let param_args: Vec<String> = model
        .params
        .fields
        .iter()
        .map(|f| format!("p.{}", f.name))
        .collect();

    out.push_str(&format!(
        "        let inner = {}_impl::{}::new({})\n",
        snake_name,
        user_struct,
        param_args.join(", ")
    ));
    out.push_str("            .expect(\"Model construction failed\");\n");
    out.push_str("        Self { inner }\n");
    out.push_str("    }\n\n");

    // Predict method
    out.push_str(&format!(
        "    fn predict(&self, i: {}Inputs) -> Result<{}Outputs, String> {{\n",
        pascal_name, pascal_name
    ));

    // Build input argument list
    let input_args: Vec<String> = model
        .inputs
        .fields
        .iter()
        .map(|f| format!("i.{}", f.name))
        .collect();

    out.push_str(&format!(
        "        let result = self.inner.predict({})?;\n",
        input_args.join(", ")
    ));

    // Build output field mapping
    let output_fields: Vec<String> = model
        .outputs
        .fields
        .iter()
        .map(|f| format!("            {}: result.{},", f.name, f.name))
        .collect();

    out.push_str(&format!("        Ok({}Outputs {{\n", pascal_name));
    out.push_str(&output_fields.join("\n"));
    out.push_str("\n        })\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // Generate the Guest impl struct (marker struct for wit_bindgen)
    out.push_str(&format!("pub struct {};\n\n", guest_struct_name));

    out.push_str(&format!(
        "impl {}Guest for {} {{\n",
        pascal_name, guest_struct_name
    ));
    out.push_str(&format!("    type Model = {};\n", adapter_name));
    out.push_str("}\n");

    out
}

/// Generate the export! macro call.
fn generate_export_macro(
    models: &[ModelInterface],
    config_map: &HashMap<&str, &ModelConfig>,
) -> String {
    let mut out = String::new();

    let exports: Vec<String> = models
        .iter()
        .filter(|m| config_map.contains_key(m.name.as_str()))
        .map(|m| format!("{}GuestImpl", m.name.to_pascal_case()))
        .collect();

    if !exports.is_empty() {
        out.push_str("// Export the guest implementations\n");
        out.push_str(&format!("export!({});\n", exports.join(", ")));
    }

    out
}

/// Write the glue code to molt-gen/lib.rs.
pub fn write_glue(project_dir: &Path, content: &str) -> Result<()> {
    let molt_gen_dir = project_dir.join("molt-gen");
    std::fs::create_dir_all(&molt_gen_dir)
        .with_context(|| format!("Failed to create molt-gen directory: {:?}", molt_gen_dir))?;

    let lib_path = molt_gen_dir.join("lib.rs");
    std::fs::write(&lib_path, content)
        .with_context(|| format!("Failed to write {:?}", lib_path))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::interface::{FieldDef, RecordDef, WitType};

    fn make_test_manifest() -> MoltManifest {
        let mut models = HashMap::new();
        models.insert(
            "drag".to_string(),
            ModelConfig {
                wit: "wit/drag.wit".into(),
                world: "drag-model".into(),
                source: "src/drag.rs".into(),
                struct_name: "DragModel".into(),
                outputs: "DragOutputs".into(),
            },
        );

        MoltManifest {
            package: crate::manifest::PackageConfig {
                name: "physics-models".into(),
                version: "0.1.0".into(),
                description: String::new(),
                authors: vec![],
                license: None,
                repository: None,
            },
            models,
            targets: HashMap::new(),
        }
    }

    fn make_test_model() -> ModelInterface {
        ModelInterface {
            name: "drag".to_string(),
            package: "myorg:physics".to_string(),
            world: "drag-model".to_string(),
            export_path: "myorg:physics/drag/model".to_string(),
            params: RecordDef {
                name: "Params".to_string(),
                fields: vec![
                    FieldDef {
                        name: "area".to_string(),
                        wit_name: "area".to_string(),
                        ty: WitType::Float64,
                        docs: None,
                    },
                    FieldDef {
                        name: "cd".to_string(),
                        wit_name: "cd".to_string(),
                        ty: WitType::Float64,
                        docs: None,
                    },
                ],
            },
            inputs: RecordDef {
                name: "Inputs".to_string(),
                fields: vec![
                    FieldDef {
                        name: "rho".to_string(),
                        wit_name: "rho".to_string(),
                        ty: WitType::Float64,
                        docs: None,
                    },
                    FieldDef {
                        name: "velocity".to_string(),
                        wit_name: "velocity".to_string(),
                        ty: WitType::Float64,
                        docs: None,
                    },
                ],
            },
            outputs: RecordDef {
                name: "Outputs".to_string(),
                fields: vec![FieldDef {
                    name: "drag_force".to_string(),
                    wit_name: "drag-force".to_string(),
                    ty: WitType::Float64,
                    docs: None,
                }],
            },
        }
    }

    #[test]
    fn test_generate_glue() {
        let manifest = make_test_manifest();
        let models = vec![make_test_model()];
        let project_dir = Path::new(".");

        let glue = generate_glue(&manifest, &models, project_dir).unwrap();

        // Check key parts of the generated code
        assert!(glue.contains("Generated by molt"));
        assert!(glue.contains("#[path = \"../src/drag.rs\"]"));
        assert!(glue.contains("mod drag_impl;"));
        assert!(glue.contains("wit_bindgen::generate!"));
        assert!(glue.contains("pub struct DragModelAdapter"));
        assert!(glue.contains("impl GuestDragModel for DragModelAdapter"));
        assert!(glue.contains("fn new(p: DragParams) -> Self"));
        assert!(glue.contains("fn predict(&self, i: DragInputs)"));
        assert!(glue.contains("pub struct DragGuestImpl"));
        assert!(glue.contains("impl DragGuest for DragGuestImpl"));
        assert!(glue.contains("export!(DragGuestImpl)"));
    }
}
